apiVersion: apps/v1
kind: Deployment
metadata:
name: weather
labels:
  app: weather
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: weather
      tier: weather
  spec:
    containers:
    - name: weather
      image: pavan96/nodeapp:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
name: weather-service
labels:
  app: weather
spec:
ports:
  - port: 3000
    targetPort: 3000
selector:
  app: weather
  tier: weather
type: LoadBalancer
