apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-weather  
  labels:    
    app: weatherapp
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec: 
     containers:
      - name: weatherapp
        image: <your-username>/mynodeapp:4
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weatherapp
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: weatherapp
